### ISSUE TITLE
App showing the wrong date.

### ISSUE THREAD

**Issue by adnansadar** [rajrajhans/weather#4]
![IMG-20190725-WA0001](https://user-images.githubusercontent.com/45177064/61870448-c3696780-aefb-11e9-85e3-defc0365d1f9.jpg)

**Comment by rajrajhans** [comment]
Well, the app gets the date from the DarkSky API itself, so this shouldn't be an issue. Turns out I was using Python's time.localtime module to convert the date from epoch (received from API) to user friendly format (DD-MM-YYYY), The time.localtime module uses system's timezone, so it was using Heroku dyno's timezone, which was set to USA by default. Now I have set the dyno's timezone to Asia / Kolkata. So it should work fine for users from Indian timezone. 

We'll need a solution to make the dates accurate for users irrespective of their timezones.

**Comment by jatanloya** [comment]
> We'll need a solution to make the dates accurate for users irrespective of their timezones.

This is indeed required because if you search the weather of 'Tokyo' the date is 25/7 and for 'San Francisco' the date is 26/7 which is clearly wrong.

A possible solution could be guessing the location of the user through general IP based trackers, to show them the date according to their respective timezone. 
This solution might fail in case of a user using a VPN connection.

A more viable solution would be to show two dates. One will be of the user and the other will be of the Destination.
Both date(s) will be according to their own respective timezones, which will avoid confusion and irregularity.

**Comment by indu-bakshi** [comment]
See when a weather app works, even if a person from India is searching the weather of USA, what is going to happen is that it will show you the weather of the date which is currently there according to our time gap. So i don't think there is a need to show the date and time according to IP because when a person of India having a IP address of india asks for the weather of USA there it gonna be a problem as the app will show the time or date of India while showing the weather result of USA.
Ps: I think the IP idea won't solve the problem rather you should do something like your program should get the current local date and time according to the search query of the user.

**Comment by rajrajhans** [comment]
Right, so if I am in India and I am searching for weather in San Fransisco, I should get date in San Fran. That way, I think the user's location is irrelevant. Or am I missing something here. @jatanloya? Plus, now we have a question of how to convert epoch to ddmmyyyy according to custom timezones.

**Comment by jatanloya** [comment]
>if I am in India and I am searching for weather in San Fransisco, I should get date in San Fran. That way, I think the user's location is irrelevant.

There is no major issue with this approach. But this creates confusion for the user since the dates for the user and the Destination might be different. Which might create the perception of "old" or "strangely new" data.
Hence using the aforementioned 2 Date system which might be a suitable solution here.

**Comment by indu-bakshi** [comment]
Look when a user of India is looking at the weather of some other place. What data would he prefer, the local time of India or the local time of that place. I think by having two dates it will create more confusion.

So you should opt for only one date and time that is on the search query based.

I agree with @jatanloya idea also but you can put that in advanced settings or something.
